import {  JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./Providers";
import Footer from "./components/Footer";
import AuthSync from "./components/AuthSync";



const jetBrains_Mono = JetBrains_Mono({
  weight:["100",'200','300', '400','500','600','700','800'],
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RealDocs || Home",
  description: "Generated by create next app realdocs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${jetBrains_Mono.className} `}
      >
        <>
        <Providers>
          <AuthSync/>
          <Navbar/>  
           {/* Main Content */}
        <main className="py-3  container mx-auto px-4">
          {children}
        </main>
        {/* Footer Section */}
        <div>
         <Footer/>
        </div>

        </Providers>
       
        </>
      </body>
    </html>
  );
}